$(function(){"use strict";function a(e){var t=$("#sys_list_related_post");t.find(".post-item").removeClass("active");t.find(".sys_p_"+e).fadeIn(function(){$(this).addClass("active").attr("style","")})}var e=$(window).width();$(window).on("resize",function(){e=$(window).width();if(e<980){$("#sys_mod_filter").removeClass("fix-top");$("#sys_tmp_height_filter").remove()}});$(window).load(function(){if($("#sys_head_slide").length>0){$("#sys_head_slide").flexslider({animation:"slide",slideshow:false,start:function(e){$(e).siblings("p").remove();$("#sys_btn_prev_slide").on("click",function(){$(e).find(".flex-prev").trigger("click");return false});$("#sys_btn_next_slide").on("click",function(){$(e).find(".flex-next").trigger("click");return false})}})}});$("#sys_filter_days_left").noUiSlider({range:[1,160],start:[1,80],step:1,connect:true,serialization:{to:[[$("#sys_min_day"),"html"],[$("#sys_max_day"),"html"]],resolution:1}}).change(function(){console.log($("#sys_filter_days_left").val())});$(".tabbable").on("click",".lbl-tab",function(){var e=$(this).index();$(this).addClass("active").siblings().removeClass("active").parents(".tabbable").find(".tab-content-item").removeClass("active").eq(e).addClass("active")});
$("#sys_head_login").on("click",function(){$("#sys_pop_login").fadeToggle(300)});$("#sys_link_reg_panel").on("click",function(){$("#sys_pop_login").find(".transport-viewer").animate({"margin-left":"-720px"},500);$("#sys_paging_state").children().removeClass("active").eq(1).addClass("active");return false});$("#sys_link_login_panel").on("click",function(){$("#sys_pop_login").find(".transport-viewer").animate({"margin-left":"0"},500);$("#sys_paging_state").children().removeClass("active").eq(0).addClass("active");return false});$("#sys_paging_state").on("click","i",function(){switch($(this).index()){case 0:$("#sys_link_login_panel").trigger("click");break;case 1:$("#sys_link_reg_panel").trigger("click");break}});$("#sys_close_login_popup").on("click",function(){$("#sys_head_login").trigger("click")});
$("#sys_selected_val").on("click",function(e){$("#sys_list_dd_cate").fadeToggle(300);$("body").on("click.hideDropCate",function(){$("#sys_list_dd_cate").fadeOut(300);$("body").off("click.hideDropCate")});e.stopPropagation()});
$("#sys_selected_val_2").on("click",function(e){$("#sys_list_dd_ville").fadeToggle(300);$("body").on("click.hideDropCate",function(){$("#sys_list_dd_ville").fadeOut(300);$("body").off("click.hideDropCate")});e.stopPropagation()});
$("#sys_list_dd_cate").on("click","a",function(e){$("#sys_selected_val").children("span").html($(this).html()).attr("data-cate-id",$(this).attr("data-cate-id"));
$("#sys_list_dd_cate").fadeOut(300);
$("body").off("click.hideDropCate");e.stopPropagation();return false});
$("#sys_list_dd_ville").on("click","a",function(e){$("#sys_selected_val_2").children("span").html($(this).html()).attr("data-ville-id",$(this).attr("data-ville-id"));
$("#sys_list_dd_ville").fadeOut(300);
$("body").off("click.hideDropCate");e.stopPropagation();return false});
/*$("#sys_apply_filter").on("click",function(){var e={keyword:$("#sys_txt_search").val(),cateId:$("#sys_selected_val").children("span").attr("data-cate-id"),minDayLeft:$("#sys_filter_days_left").val()[0],maxDayLeft:$("#sys_filter_days_left").val()[1]};console.log(e)});*/



var t=$("#sys_mod_filter");if(t.length>0){var n=$("#sys_mod_filter").offset().top;$(window).on("scroll",function(){if(e>980){var r=window.pageYOffset!==undefined?window.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop;if(r>n){t.addClass("fix-top");if($("#sys_tmp_height_filter").length<=0){$("<div id='sys_tmp_height_filter'></div>").height($("#sys_mod_filter").outerHeight(true)).insertAfter("#sys_mod_filter")}}else{t.removeClass("fix-top");$("#sys_tmp_height_filter").remove()}}})}var r=$("#sys_warning_sms");if(r.length>0){var i=r.attr("data-warning-txt").split(",");var s=0;r.html(i[s]);setInterval(function(){if(s==i.length-1){s=0}else{s++}r.fadeOut(300,function(){$(this).html(i[s]);$(this).fadeIn(300)})},3e3)}if($("#mp-menu").length>0)new mlPushMenu(document.getElementById("mp-menu"),document.getElementById("sys_btn_toogle_menu"),{dockSide:"right"});

//var o=$("#container_list_link");if(o.length>0){o.masonry({itemSelector:".grp-by-alpha"})}

var u=$("#sys_list_related_post");if(u.length>0){$("#sys_prev_replated_page").on("click",function(){var e=u.attr("data-paging");var t=u.attr("data-total-page");if(e==1)e=t;else e--;u.attr("data-paging",e);a(e);return false});$("#sys_next_replated_page").on("click",function(){var e=u.attr("data-paging");var t=u.attr("data-total-page");if(e==t)e=1;else e++;u.attr("data-paging",e);a(e);return false})}})